<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FilmsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return array
     */
    public function run()
    {
     $film = [
       [
        'type_id' => 1,
        'title' => 'Криминальное чтиво',
        'slug' => 'kriminalnoe-chtivo',
        'description' => 'Черная комедия Квентина Тарантино рассказывает о криминальных буднях двух бандитов – Винсента Вега (Джон Траволта) и Джулса Винфилда (Сэмюэль Л. Джексон). Они проводят время в философских беседах в перерыве между разборками и "решением проблем" с должниками своего криминального босса Марселласа Уоллеса. Параллельно разворачивается три истории.',
        'year' => 1994,
        'country' => 'США',
        'age_limit' => '18',
        'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/1612526-1436405.jpg',
        'trailer' => 'https://www.film.ru/sites/default/files/trailers/1612526/Pulp%20Fiction%20Trailer%20Rus.mp4',
       ],
       [
         'type_id' => 1,
         'title' => 'Главный герой',
         'slug' => 'svobodnyy-paren',
         'description' => 'В центре сюжета окажется обычный сотрудник банка, который погряз в повседневной рутине. Но однажды его представление о мире меняется, когда он узнаёт, что всё вокруг является частью большой видеоигры, где каждый может делать всё, что вздумается. И теперь судьба человечества находится в его руках. Вот только он — всего лишь второстепенный персонаж.',
         'year' => 2021,
         'country' => 'США',
         'age_limit' => '16',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/44775437-2070383.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/44775437/aptechka.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Крик',
         'slug' => 'scream',
         'description' => 'По сюжету убийца в маске по прозвищу Призрачное лицо возвращается и вновь начинает орудовать своим ножом. Героям предстоит выяснить, кто скрывается под капюшоном, и, конечно же, выжить.',
         'year' => 2021,
         'country' => 'США',
         'age_limit' => '18',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/49609853-1740030.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/49609853/screem-2022-trailer-final.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Матрица: Воскрешение',
         'slug' => 'matrica-reborn',
         'description' => 'Что делать, если окружающий мир кажется ловушкой, а самые фантастические сны больше похожи на настоящую жизнь, чем повседневная реальность? Хочешь найти правду? Следуй за белым кроликом, чтобы вернуться туда, где все началось… Обратно в Матрицу.',
         'year' => 2021,
         'country' => 'США',
         'age_limit' => '6',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/47996050-1705989.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/47996050/The_Matrix_Resurrections_-_The_Game_Awards_Clip_0.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Зверопой 2',
         'slug' => 'sing-2',
         'description' => 'По сюжету первой части коала Бастер Мун собрал самых талантливых зверей города, чтобы они приняли участие в его песенном шоу. Несмотря на все трудности, он собрал свою команду не только выдающихся музыкантов, но и преданных друзей. И в новом мультфильме их приключения продолжатся. А ещё зрителей ждёт куда больше хитов.',
         'year' => 2021,
         'country' => 'США',
         'age_limit' => '6',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/27740261-1703068.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/27740261/Sing-2-rus-3.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Последняя дуэль',
         'slug' => 'the-last-duel',
         'description' => 'В основе сюжета лежит одноимённый роман Эрика Ягера. Фильм расскажет о рыцаре Жане де Карруже, который возвращается с войны и узнаёт, что его сосед Жак Ле Гри изнасиловал его жену. Однако он никак не может доказать его вину и обращается за помощью к королю Карлу VI, который считает, что спор должен быть разрешён дуэлью.',
         'year' => 2021,
         'country' => 'США',
         'age_limit' => '6',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/27740261-1703068.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/49462045/The-Last-Duel-trailer-rus.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Не время умирать',
         'slug' => 'bond-25',
         'description' => 'В 25-м фильме бондианы агент 007 решает уйти в отставку и отдыхает на Ямайке, однако внезапно его отдых прерывают зовом о помощи, и Джеймс Бонд вынужден вернуться на службу. Он возвращается к своей роли супершпиона, чтобы спасти мир от загадочного злодея по имени Сафин.',
         'year' => 2021,
         'country' => 'США',
         'age_limit' => '12',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/28421864-1671801.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/28421864/No-Time-to-Die-Trailer_Rus-final.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Красотка на взводе',
         'slug' => 'jolt',
         'description' => 'Линди — вышибала, которая имеет проблемы с управлением гневом и поэтому боится убить кого-то. Поэтому, чтобы контролировать себя, она носит специальный жилет с разрядом, который успокаивает её, если ситуация выходит из-под контроля. Но когда убивают её возлюбленного, она снимает его и отправляется на поиски убийцы.',
         'year' => 2021,
         'country' => 'США',
         'age_limit' => '12',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/47859547-2070380.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/47859547/Jolt-rus.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Легенда о Зеленом рыцаре',
         'slug' => 'the-green-knight',
         'description' => 'Картина рассказывает о том, как в Камелот во время Нового года заявляется таинственный Зелёный рыцарь, который предлагает всем собравшимся пари. Любой может ударить его топором, но спустя год рыцарь вернётся, чтобы нанести свой ответный удар. Юный сэр Гавейн принимает вызов и отрубает гостю голову, но тот ставит её на место и уходит. Тогда главный герой отправляется в своё путешествие, чтобы в назначенный срок встретиться с врагом.',
         'year' => 2021,
         'country' => 'США',
         'age_limit' => '12',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/49485026-2070374.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/49485026/Green-Knight-trailer-rus-2.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Отряд самоубийц: Миссия навылет',
         'slug' => 'otryad-samoubiyc-2',
         'description' => 'Есть на земле одно гнилое место, откуда мечтают свалить даже самые отъявленные злодеи. Тюрьма Белль Рив — для преступников со сверхспособностями. Она же — ад. Она же — база рекрутов для суперсекретного проекта «Отряд самоубийц',
         'year' => 2021,
         'country' => 'США',
         'age_limit' => '16',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/27874051-1963226.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/27874051/The-Suicide-Squad-Trailer-rus-2.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Титан',
         'slug' => 'titane',
         'description' => 'Отец Алексии полностью игнорирует существование своей дочери, стараясь избегать любого контакта с ней, несмотря на то, что они живут под одной крышей. Как следствие, в будущем Алексия холодно реагирует на близость, ее языком любви становится проявление физического насилия. Когда такой способ коммуникации заходит слишком далеко, Алексии приходится бросится в бега, меняя свой облик до неузнаваемости: она бреет голову утягивает грудь эластичным бинтом, становясь похожей на парня. ',
         'year' => 2021,
         'country' => 'США',
         'age_limit' => '16',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/49744865-2070386.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/49744865/Titane-Trailer-rus.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Герда',
         'slug' => 'gerda',
         'description' => 'Драма о студентке социологического института, которая сбегает от невыносимо несчастливой жизни в светлые сны.',
         'year' => 2021,
         'country' => 'Россия',
         'age_limit' => '18',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/49564572-2070392.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/49564572/gerda-2021.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Фарго',
         'slug' => 'fargo',
         'description' => 'Для робкого менеджера по продажам, работающего у собственного тестя, похищение собственной жены — отличная идея. Он нанимает двух преступников, чтобы по результатам разделить с ними крупный выкуп за заложницу. Но дело сразу идет не так, как замышлялось, проливается кровь… Вызов преступникам бросает отважная женщина-полицейский…',
         'year' => 1996,
         'country' => 'США',
         'age_limit' => '18',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/1620931-1546416.jpeg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/1620931/Fargo-Trailer.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Джеки',
         'slug' => 'dzheki',
         'description' => 'Жаклин Кеннеди, «Джеки» или Жаклин О, как ее еще называли современники, была первой леди США с 1961 по 1963 год. Одна из самых популярных женщин своего времени, законодательница моды, красоты и изящества в Америке и Европе, героиня светской хроники. Про нее написаны десятки книг и снято немало фильмов. Эта история повествует о событиях, которые разворачивается в течение четырёх трагических ноябрьских дней после убийства Джона Кеннеди в Далласе 22 ноября 1963 года.',
         'year' => 2016,
         'country' => 'США',
         'age_limit' => '18',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/20169294-1436419.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/20169294/jackie.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Лок',
         'slug' => 'lok',
         'description' => 'Иван Лок жил обычной жизнью, пока буквально в одно мгновение не оказался практически на волосок от гибели. Таинственный телефонный звонок положил начало гонке на время ради спасения его собственной жизни. У героя есть только девяносто минут…',
         'year' => 2013,
         'country' => 'США',
         'age_limit' => '12',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/2178055-1436403.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/2178055/Locke-Clip.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Скотт Пилигрим против всех',
         'slug' => 'skott-piligrim-protiv-vseh',
         'description' => 'Спокойная жизнь 22-летнего Скотта Пилигрима, безработного басиста не слишком известной рок-группы, подошла к концу - он влюбился в девушку своей мечты. Но любовь к красавице Рамоне связана с нешуточной опасностью: между Скоттом и девушкой стоят семь ее злобных "бывших", которых парню предстоит одолеть, узнав, попутно, что Рамона обладает очень необычными способностями.',
         'year' => 2010,
         'country' => 'США',
         'age_limit' => '12',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/1628845-1436372.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/1628845/Scott-Pilgrim-vs-the-World-Trailer.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Мастер',
         'slug' => 'master',
         'description' => 'Демобилизованный моряк с загадочным прошлым не может найти места в послевоенной Америке. Он меняет одну работу за другой, пока случайно не знакомится с харизматичным создателем религиозного культа, известным писателем и философом. К удивлению приверженцев модного учения, их гуру делает агрессивного маргинала своим ближайшим помощником. По мере того как новая вера завоевывает поклонников, бывший бродяга начинает задаваться вопросами о том, во что он верит, и кем является его наставник на самом деле. Но некоторым тайнам лучше оставаться нераскрытыми…',
         'year' => 2012,
         'country' => 'США',
         'age_limit' => '18',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/1633620-1436402.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/1633620/Master%20trl%20Ru.mp4',
       ],
	[
         'type_id' => 1,
         'title' => 'Повелитель бури',
         'slug' => 'povelitel-buri',
         'description' => 'Элитное армейское подразделение саперов ведет войну в Ираке и оказывается в городе где каждый встречный – потенциальный враг и шахид, и каждый предмет может быть замаскированной бомбой.',
         'year' => 2008,
         'country' => 'США',
         'age_limit' => '6',
         'image' => 'film.ru/sites/default/files/styles/thumb_260x400/public/movies/posters/1627638-1436378.jpg',
         'trailer' => 'https://www.film.ru/sites/default/files/trailers/1627638/The-Hurt-Locker-Trailer.mp4',
       ],
      ];
      DB::table('films')->insert($film);
    }

}
